# Generated by Django 5.0.6 on 2024-06-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_seasonresult_avgquali_seasonresult_avgresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverId', models.CharField(blank=True, max_length=64)),
                ('constructorId', models.CharField(blank=True, max_length=64)),
                ('avgResult', models.FloatField(default=list)),
                ('avgQuali', models.FloatField(default=list)),
            ],
        ),
    ]
