# Generated by Django 5.0.6 on 2024-06-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_currentseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentseason',
            name='roundNumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
