# Generated by Django 5.0.6 on 2024-06-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0006_currentseason_roundnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentseason',
            name='avgQuali',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='currentseason',
            name='avgResult',
            field=models.FloatField(blank=True),
        ),
    ]
