# Generated by Django 5.0.6 on 2024-06-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0008_currentstandings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrentStandings',
            new_name='CurrentStanding',
        ),
    ]
