# Generated by Django 5.0.6 on 2024-06-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0009_rename_currentstandings_currentstanding'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverId', models.CharField(max_length=64)),
                ('flag', models.ImageField(upload_to='')),
                ('signature', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TrackProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackId', models.CharField(max_length=64)),
                ('flag', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
    ]
