# Generated by Django 5.0.6 on 2024-06-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0010_driverprofile_trackprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='title',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='conLogo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackprofile',
            name='trackMap',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
