# Generated by Django 5.0.6 on 2024-06-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0012_remove_driverprofile_conlogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='driverImage',
            field=models.ImageField(upload_to='images/profiles/'),
        ),
        migrations.AlterField(
            model_name='trackprofile',
            name='trackImage',
            field=models.ImageField(upload_to='images/profiles/'),
        ),
    ]
